### ISSUE TITLE
pandas - DataFrame to CanvasXpress

### ISSUE THREAD

**Issue by neuhausi** [docinfosci/canvasxpress-python#32]
It would be great to have a method to convert a pandas DataFrame to a CanvasXpress JSON object

**Comment by docinfosci** [comment]
Thanks!

I realize that in creating CXDataFrameData I made assumptions based on my experience with other charting frameworks about how CanvasXpress would address simply two dimensional matrix data. and that for more advanced arrangements one would switch to JSON-like structures (e.g., `dict`).

For example, given the simple 2D matrix:
```python
from pandas import DataFrame
value_by_day = DataFrame(
    {
         'date': [str(start_date + timedelta(days=day_count)) for day_count in range(7)],
         'value': [uniform((i + 1) / 2, i + 1) for i in range(7)],
     }
)
```

This would be converted into (via an internal `to_dict(orient='list')`):
```python
{
    "date": [
        "2020-01-01",
        "2020-01-02",
        "2020-01-03",
        "2020-01-04",
        "2020-01-05",
        "2020-01-06",
        "2020-01-07"
    ],
    "value": [
        0.8992288670090968,
        1.9103500465168564,
        1.5203539750635664,
        2.338291164924815,
        4.946006330382968,
        4.322574996895838,
        3.690717514571863
    ]
}
```

From there, I figured that one could use attributes to assign y and x from the data set; or that CanvasXpress would use implied mapping, such as:

`date` -> 
```python
{
        "y" : {
            "vars" : [""],
            "smps" : [
                "2020-01-01",
                "2020-01-02",
                "2020-01-03",
                "2020-01-04",
                "2020-01-05",
                "2020-01-06",
                "2020-01-07"
            ],
            "data" : [
                [
                    0.8992288670090968,
                    1.9103500465168564,
                    1.5203539750635664,
                    2.338291164924815,
                    4.946006330382968,
                    4.322574996895838,
                    3.690717514571863
                ],
            ]
        }
    }
```

This is what I can assume with some other Python charting frameworks.

It seems it doesn't work that way.  Alas, the automated tests don't detect exceptions (etc.) when this kind of scenario is provided and mostly I've been working with dict/JSON formats for manual testing.  Pure coincidence.

We can handle this conversion internally, however.  I intend to do the following:

1. Update the automated test framework with this and a few other examples
2. Do some additional manual testing focused on this
3. Provide an implied conversion similar to the above for 2D data brought in via a matrix.  (I see that CanvasXpress does not crash if text:text data is provided using a line chart example, so I'll proceed with the conversion without checks.
4. Also add DataFrame handling appropriate to panels for 3D+ versus assuming the user would switch to dict/JSON.

ttys

**Comment by docinfosci** [comment]
A solution has been developed, and is now in testing.  DEV previews will be published to pypi.org and readthedocs.org once automated tests are satisfied—likely Friday at the latest.

CXData has been refined to coordinate with an optional CXDataProfile.  CXDataProfile understands the requirements of the CanvasXpress JSON data object structure, and when employed makes adjustments to the Python tier data so that it matches the expectations of the Javascript.  This enhancement is done in a manner to be transparent to developers who don't know or care about the complexity, yet is easily accessible for developers who demand more customization at the Python tier prior to rendering structures to Javascript.

Given matrix data, the profile will add a `y` attribute and populate `vars` and `smps` to match either the information provided by the matrix or reasonable inferences based on the data.

Given key-pair data, the profile will check for a `y` attribute and if that is missing add a contextual wrapper.  It additionally checks for `vars`, `smps`, and `data` attributes and adds or adjusts those as appropriate.

One profile currently exists, CXStandardProfile, and it addresses the standard profile for CanvasXpress JSON data.  Additional profiles will be added to handle special cases such as Venn expectations.  

The developer can also override attributes such as `vars` provided by the data with custom values, plus force validation to ensure things line up should that be interesting.

The examples section will be expanded with:

* Default data approaches where the developer knows the CanvasXpress JSON format and accommodates such in the data itself (such as what might be typical for iris data downloaded from the CanvasXpress for Javascript github.com site).
* Advanced approaches by which various combinations of `vars` and `smps` are missing or provided or overridden.  

Once this has been properly tested and released, likely in a few days, the additional attributes of `x` and `z` will be handled in the profiles.  Essential cases using various key-pair and matrix data look good, but coverage needs to be increased before the release will be permitted by the build harness.

This strategy allows developers properly familiar with CanvasXpress requirements to use pre-formatted data for the simplest use case; right now only key-pair data, such as CXDictData, accommodates that scenario.  However, given that Python tier data sources are not likely to be CanvasXpress aware (especially legacy sources), the developer can—with this update—now accommodate CanvasXpress' requirements either through inferred handling by the profiler or explicit handling by the developer.

I'll update this thread once appropriately detailed examples are available at ReadTheDocs.

**Comment by docinfosci** [comment]
The github branch with the work being performed for the above remarks:
https://github.com/docinfosci/canvasxpress-python/tree/2021-05-18-cx-json-format-options

**Comment by docinfosci** [comment]
The initial solution, which mainly benefits matrix data, has been released into production!

* https://github.com/docinfosci/canvasxpress-python/tree/main
* https://pypi.org/project/canvasxpress/
* https://canvasxpress-python.readthedocs.io/en/latest/

For a complete CanvasXpress JSON data object, the approach to use is CXDictData or CXJSONData.  These permit full JSON-like data structures that can be tailored exactly to requirement.  The associated profile, CXStandardProfile, will attempt to rebuild missing `y` attributes; and it will honour existing `x` and `x` attributes at the root level.

For matrix data, the associated profile will infer `y` attributes such as `vars` and `smps` from the data.

In either case, developers can override `vars` and `smps` values provided in the data (or inherent to the data) using the profile's properties.  For example:

```python
chart.data.profile.smps = ['Monday', 'Tuesday']
```

Extensive examples are available on [ReadTheDocs](https://canvasxpress-python.readthedocs.io/en/latest/data/).

For completeness, here's a series of manual tests that can be performed in Jupyter (and are in fact part of the manual test suite):

To pull in CanvasXpress (and don't forget to restart the kernal after execution):

```python
import sys
# Install a pre-release edition of canvasxpress
# !{sys.executable} -m pip install -U -i https://test.pypi.org/simple/ "canvasxpress==2021.5.20.dev204834"

# Install a standard release edition of canvasxpress
!{sys.executable} -m pip install -U canvasxpress

# List all packages in the environment to confirm installation
!{sys.executable} -m pip list
```

To validate reasonable key-pair scenarios:

```python
import json

from canvasxpress.canvas import CanvasXpress
from canvasxpress.config.collection import CXConfigs
from canvasxpress.config.type import CXGraphType, CXGraphTypeOptions
from canvasxpress.data.keypair import CXDictData
from canvasxpress.render.jupyter import CXNoteBook

# Define a CX bar chart with some basic data
chart: CanvasXpress = CanvasXpress(
    render_to="dict_chart",
    config=CXConfigs(
        CXGraphType(CXGraphTypeOptions.Bar)
    )
)
dict_nb = CXNoteBook(chart)
    
chart.data = CXDictData(
    {
        "y": {
            "vars": ["Gene1"],
            "smps": ["Smp1", "Smp2", "Smp3"],
            "data": [[10, 35, 88]]
        },
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "y": {
            "smps": ["Smp1", "Smp2", "Smp3"],
            "data": [[10, 35, 88]]
        },
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "y": {
            "vars": ["Gene1"],
            "data": [[10, 35, 88]]
        },
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "vars": ["Gene1"],
        "smps": ["Smp1", "Smp2", "Smp3"],
        "data": [[10, 35, 88]]
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "smps": ["Smp1", "Smp2", "Smp3"],
        "data": [[10, 35, 88]]
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "vars": ["Gene1"],
        "data": [[10, 35, 88]]
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "vars": ["Gene1"],
        "values": [[10, 35, 88]]
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "values": [[10, 35, 88]]
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        "values": {"coin":"penny"}
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()

chart.data = CXDictData(
    {
        
    }
)
print(json.dumps(chart.data.render_to_dict(), indent=4))
dict_nb.render()
```

To review matrix transformation:

```python
import pandas 
from pandas import DataFrame
import json

from datetime import date, timedelta
from random import uniform

from canvasxpress.canvas import CanvasXpress
from canvasxpress.config.collection import CXConfigs
from canvasxpress.config.type import CXGraphType, CXGraphTypeOptions
from canvasxpress.data.matrix import CXDataframeData
from canvasxpress.data.keypair import CXDictData
from canvasxpress.render.jupyter import CXNoteBook

# Generate a set of values over a 90-day period
start_date = date(2020, 1, 1)
header = [
    str(start_date + timedelta(days=i))
    for i in range(6)
]
content = [
    [
        uniform((i + 1) / 2, i + 1)
        for i in range(6)
    ],
    [
        uniform((i + 1) / 2, i + 1)
        for i in range(6)
    ]
]

values_by_day = DataFrame(
    content,
    columns=header
)

print("DataFrame:")
print(values_by_day)

sample = CXDataframeData(values_by_day)

print()
print("CX Data Perspective")
print(json.dumps(sample.render_to_dict(), indent=4))

# Configure a spark line
chart_options = CXConfigs()
chart_options \
    .set_param("graphOrientation", "vertical") \
    .set_param("graphType", "Line") \
    .set_param("title", "Line Graphs")

# Create the chart
chart = CanvasXpress(
    render_to="line_chart",
    data=sample,
    config=chart_options
)

# Render into Jupyter
line_nb = CXNoteBook(chart)
line_nb.render()


# Change the variables
print()
sample.profile.vars = ["Gas Trucks", "Electric Trucks"]
print(json.dumps(sample.render_to_dict(), indent=4))
line_nb.render()

# Change the samples
print()
sample.profile.vars = None
sample.profile.smps = ['A', 'B', 'C', 'D', 'E', 'F']
print(json.dumps(sample.render_to_dict(), indent=4))
line_nb.render()
```

Per the [PyPI.org homepage for CanvasXpress](https://pypi.org/project/canvasxpress/), the next steps are to provide dedicated support for `x` and `z` attributes, as well as to create profile components specific to the correlation and venn diagram data formats.  This mainly impacts matrix data components, given that key-pair values for such will be passed-through, but overall robustness/flexibility will be provided.

Given that this resolves the fundamental aspect of matrix data at the Python tier being provided to the CanvasXpress Javascript tier I think this issue can be closed.  If you agree after this week I'll do so—or feel welcome to do so.

Cheers!

**Comment by docinfosci** [comment]
Hello!  This is a confirmation that in the time since the last update the package has been enhanced to provide support for a variety of Python native datatypes, such as dict, as well as Python extended types, such as Pandas' DataFrame.

Examples are at: 
- https://canvasxpress-python.readthedocs.io/en/latest/examples/
- https://canvasxpress-python.readthedocs.io/en/latest/data/

Please feel welcome to reach out if you feel this issue is not resolved; however, given the above and our discussions I will consider this issue closed.

Have a great day!
@docinfosci

**Comment by docinfosci** [comment]
Resolved with the addition of support for Python native objects, such as dict, and extension objects, such as DataFrame.  Documentation is available at https://canvas-express.readthedocs.org.
